# Generated by Django 3.1.2 on 2020-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
